"""Generate user documentation from the runtime MCP registry."""

from pathlib import Path

from attocode_intel.catalog import DAILY, is_write, remote_available, tool_catalog

lines = [
    "# Intelligence tool catalog",
    "",
    "Generated by `packages/code-intel/scripts/generate_catalog.py`. Re-run after changing tools or profiles.",
    "",
    "| Tool | Profile | Remote | Access |",
    "|---|---|---|---|",
]
for tool in sorted(tool_catalog(), key=lambda item: item.name):
    profile = (
        "daily + full"
        if tool.name in DAILY
        or tool.name in {"capabilities", "update_learning", "cross_repo_search"}
        else "full"
    )
    lines.append(
        f"| `{tool.name}` | {profile} | {'yes' if remote_available(tool.name) else 'local only'} | {'write' if is_write(tool.name) else 'read'} |"
    )
Path("docs/intelligence-tools.md").write_text("\n".join(lines) + "\n")
