/**
 * Lesson 18: ReAct Pattern Types
 *
 * Type definitions for the ReAct (Reasoning + Acting) pattern.
 * ReAct interleaves reasoning traces with actions, making the
 * agent's decision-making process explicit and traceable.
 */

import type { ToolDefinition, ToolResult } from '../03-tool-system/types.js';

// =============================================================================
// CORE REACT TYPES
// =============================================================================

/**
 * A single step in the ReAct loop.
 * Each step consists of: Thought → Action → Observation
 */
export interface ReActStep {
  /** Step number (1-indexed) */
  stepNumber: number;

  /** The agent's reasoning about what to do next */
  thought: string;

  /** The action taken (tool call) */
  action: ReActAction;

  /** The result of the action */
  observation: string;

  /** When this step was executed */
  timestamp: Date;

  /** Duration of the step in milliseconds */
  durationMs: number;
}

/**
 * An action in the ReAct pattern.
 * This represents a tool call with explicit reasoning.
 */
export interface ReActAction {
  /** Tool name to invoke */
  tool: string;

  /** Tool arguments */
  args: Record<string, unknown>;

  /** Raw action string as generated by the LLM */
  raw?: string;
}

/**
 * The complete trace of a ReAct execution.
 */
export interface ReActTrace {
  /** The original goal/task */
  goal: string;

  /** All steps taken */
  steps: ReActStep[];

  /** The final answer/result */
  finalAnswer: string;

  /** Whether the goal was achieved */
  success: boolean;

  /** Total execution time in milliseconds */
  totalDurationMs: number;

  /** Number of tool calls made */
  toolCallCount: number;

  /** Any errors encountered */
  errors: ReActError[];
}

/**
 * An error that occurred during ReAct execution.
 */
export interface ReActError {
  stepNumber: number;
  type: 'parse' | 'tool' | 'timeout' | 'max_steps';
  message: string;
  recoverable: boolean;
}

// =============================================================================
// REACT AGENT CONFIGURATION
// =============================================================================

/**
 * Configuration for a ReAct agent.
 */
export interface ReActConfig {
  /** Maximum number of steps before stopping */
  maxSteps: number;

  /** Timeout per step in milliseconds */
  stepTimeout: number;

  /** Whether to include observations in the prompt */
  includeObservations: boolean;

  /** Maximum observation length before truncation */
  maxObservationLength: number;

  /** Prompt template configuration */
  promptConfig: ReActPromptConfig;

  /** Whether to enable verbose logging */
  verbose: boolean;
}

/**
 * Configuration for ReAct prompts.
 */
export interface ReActPromptConfig {
  /** System prompt prefix */
  systemPrefix: string;

  /** Format instructions for the agent */
  formatInstructions: string;

  /** Examples to include (few-shot) */
  examples?: ReActExample[];

  /** Suffix added after each step */
  stepSuffix: string;
}

/**
 * A few-shot example for the ReAct prompt.
 */
export interface ReActExample {
  goal: string;
  steps: Array<{
    thought: string;
    action: string;
    observation: string;
  }>;
  finalAnswer: string;
}

// =============================================================================
// PARSING TYPES
// =============================================================================

/**
 * Result of parsing LLM output for ReAct format.
 */
export interface ParsedReActOutput {
  /** Whether parsing was successful */
  success: boolean;

  /** Extracted thought (if found) */
  thought?: string;

  /** Extracted action (if found) */
  action?: ReActAction;

  /** Whether this is a final answer */
  isFinalAnswer: boolean;

  /** Final answer content (if isFinalAnswer is true) */
  finalAnswer?: string;

  /** Parse errors if any */
  errors: string[];

  /** Raw output from the LLM */
  raw: string;
}

/**
 * Patterns for extracting ReAct components.
 */
export interface ReActPatterns {
  /** Pattern to match thought */
  thought: RegExp;

  /** Pattern to match action */
  action: RegExp;

  /** Pattern to match final answer */
  finalAnswer: RegExp;

  /** Pattern to extract tool name from action */
  toolName: RegExp;

  /** Pattern to extract arguments from action */
  toolArgs: RegExp;
}

// =============================================================================
// OBSERVATION FORMATTING
// =============================================================================

/**
 * Options for formatting observations.
 */
export interface ObservationFormatOptions {
  /** Maximum length before truncation */
  maxLength: number;

  /** How to truncate */
  truncation: 'end' | 'middle' | 'summarize';

  /** Whether to format as code block */
  asCodeBlock: boolean;

  /** Whether to include metadata */
  includeMetadata: boolean;
}

/**
 * Formatted observation result.
 */
export interface FormattedObservation {
  /** Formatted observation string */
  content: string;

  /** Whether it was truncated */
  truncated: boolean;

  /** Original length */
  originalLength: number;
}

// =============================================================================
// REACT LOOP EVENTS
// =============================================================================

/**
 * Events emitted during ReAct execution.
 */
export type ReActEvent =
  | { type: 'start'; goal: string }
  | { type: 'thought'; stepNumber: number; thought: string }
  | { type: 'action'; stepNumber: number; action: ReActAction }
  | { type: 'observation'; stepNumber: number; observation: string }
  | { type: 'step_complete'; step: ReActStep }
  | { type: 'final_answer'; answer: string }
  | { type: 'error'; error: ReActError }
  | { type: 'complete'; trace: ReActTrace };

/**
 * Listener for ReAct events.
 */
export type ReActEventListener = (event: ReActEvent) => void;

// =============================================================================
// TOOL INTEGRATION
// =============================================================================

/**
 * Tool registry interface for ReAct.
 */
export interface ReActToolRegistry {
  /** Get a tool by name */
  get(name: string): ToolDefinition | undefined;

  /** Get all tool names */
  names(): string[];

  /** Get tool descriptions for the prompt */
  getDescriptions(): string;

  /** Execute a tool */
  execute(name: string, args: Record<string, unknown>): Promise<ToolResult>;
}

// =============================================================================
// COMPARISON TYPES
// =============================================================================

/**
 * Comparison between ReAct and standard execution.
 */
export interface ReActComparison {
  goal: string;

  /** ReAct execution results */
  react: {
    trace: ReActTrace;
    success: boolean;
    answer: string;
  };

  /** Standard execution results */
  standard: {
    iterations: number;
    toolCalls: number;
    success: boolean;
    answer: string;
  };

  /** Analysis of differences */
  analysis: {
    reactAdvantages: string[];
    standardAdvantages: string[];
    recommendation: 'react' | 'standard' | 'either';
  };
}

// =============================================================================
// DEFAULT VALUES
// =============================================================================

/**
 * Default ReAct configuration.
 */
export const DEFAULT_REACT_CONFIG: ReActConfig = {
  maxSteps: 10,
  stepTimeout: 30000,
  includeObservations: true,
  maxObservationLength: 1000,
  verbose: false,
  promptConfig: {
    systemPrefix: '',
    formatInstructions: '',
    stepSuffix: '',
  },
};

/**
 * Default patterns for parsing ReAct output.
 */
export const DEFAULT_REACT_PATTERNS: ReActPatterns = {
  thought: /Thought:\s*(.+?)(?=Action:|$)/is,
  action: /Action:\s*(.+?)(?=Observation:|$)/is,
  finalAnswer: /Final Answer:\s*(.+?)$/is,
  toolName: /^(\w+)\s*\(/,
  toolArgs: /\((.+)\)$/s,
};

// =============================================================================
// RE-EXPORTS
// =============================================================================

export type { ToolDefinition, ToolResult } from '../03-tool-system/types.js';
